server:
  port: 8083

spring:
  main:
    web-application-type: reactive

  application:
    name: api-gateway

  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: USER
          uri: lb://USER
          predicates:
            - Path=/api/v1/user/**
        - id: POST
          uri: lb://POST
          predicates:
            - Path=/api/v1/post/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

