package com.devkenya.clients.notification;

public enum NotificationType {
    WElCOME,
    PASSWORD_RESET,
    PASSWORD_CHANGED,
    EMAIL_VERIFICATION,
    EMAIL_VERIFIED,
    PHONE_VERIFICATION,
    PHONE_VERIFIED,
    PROJECT_CREATED,
    PROJECT_INVITATION,
    PROJECT_INVITATION_ACCEPTED,
    PROJECT_INVITATION_REJECTED,
    PROJECT_INVITATION_EXPIRED,

    PROJECT_INVITATION_REMINDER,

    PROJECT_FUNDED,

    PROJECT_STATUS_CHANGED,

    PROJECT_APPROVED,

    PROJECT_REJECTED,

    PROJECT_COMPLETED,
    PAYMENT_RECEIVED,
    PAYMENT_RELEASED,
}
